appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WdvUvSO4/VE65rl1KcZ+t4oQOrCKpv7/0ar2UaYwul5ASqiufIlyH19hmKzcnQX17aYmw8G3M0RyTy/fVKJdUjtRrKTplfAgsz6G3hIKjl8mp4KkxtU01MpLXBk8OrEGCePYtDj6D7Yn9uTmLtp8BJqwWgsOFki8R3tbJOtP3gPh8AiYWNY5v+qcQbJilb+AEFpGWcmHwMsFHg1oiFrwyf8ahp0i69a3hIBz70ju9wwA96+fAeGA/liIbipscwrGmDvHR33mfixnzagv2LHTZWMPG59+HtQQNhnRvEyvVrd6jlKrilcO+jfAb/S0lmHiBN9yljyjlMNS/dvX8qeL9L7METDZ9XmDp04dq212VmQfR6X3vPAsvZFiX5SOGiT4ojM2mmnDWKRVa8qvKwFOKTbMb6MpV/aS5os7vncThP/onD2F9PyCZTEzD0BFq2mCfPnyJD/Jccl/nS/FLfKmcA4r4/hYE0om6Zkc0qxKk/taMoQ95COh3HX35gKfngXkepq/7OnWRxE1l7mwKAzQMfgWBFLIJkPIA3Ojee6HB4Tipu1WZhDtIVOy5KZpoY9yLm6yJ+B4V8ZI2bA+YKmLLw/sp9zojqpLU6JUF+Wl8Bys9fqcS62/PHJh2awicHFjX9WBItZyrTu9M9+OV5dpJvIqRhVjXc+cnmYI3EsGXlU=}
conda_forge_output_validation: true
